changelog:
  exclude:
    labels:
      - dependencies
      - skip-changelog
  categories:
    - title: Features
      labels:
        - feature
        - feat
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
        - fix
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: CI / Tooling
      labels:
        - ci
        - tooling
    - title: Other Changes
      labels:
        - "*"
