ci:
  autofix_prs: false
  autoupdate_schedule: quarterly

repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 5e2fb545eba1ea9dc051f6f962d52fe8f76a9794  # v0.15.13
  hooks:
    # Run the linter.
    - id: ruff-check
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
- repo: https://github.com/MarcoGorelli/auto-walrus
  rev: 1743edbed52f3d61886b59d98a27164a8af29c0d  # frozen: 0.4.1
  hooks:
    - id: auto-walrus
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: dd18dad857d6133e90bbe478f4f2f22ec0030269  # v22.1.5
  hooks:
    - id: clang-format
      exclude: ^(ports/doom/|user/static/)
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # v6.0.0
  hooks:
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-executables-have-shebangs
    - id: check-merge-conflict
    - id: check-shebang-scripts-are-executable
    - id: check-toml
    - id: check-vcs-permalinks
    - id: check-yaml
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: mixed-line-ending
      args: [--fix=no]
    - id: name-tests-test
      args: [--pytest-test-first]
      files: ^tests/unit/.*\.py$
    - id: no-commit-to-branch
    - id: trailing-whitespace
