repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.13  # v0.15.13
  hooks:
    # Run the linter.
    - id: ruff-check
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
- repo: https://github.com/MarcoGorelli/auto-walrus
  rev: 0.4.1  # 0.3.4
  hooks:
    - id: auto-walrus
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v22.1.5  # v22.1.5
  hooks:
    - id: clang-format
      exclude: ^(tools/doom/|static/)
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0  # v6.0.0
  hooks:
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-executables-have-shebangs
    - id: check-merge-conflict
    - id: check-shebang-scripts-are-executable
    - id: check-toml
    - id: check-vcs-permalinks
    - id: check-yaml
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: mixed-line-ending
      args: [--fix=no]
    - id: name-tests-test
      args: [--pytest-test-first]
      files: ^tests/unit/.*\.py$
    - id: no-commit-to-branch
    - id: trailing-whitespace
